independent_first_frame: false
warp_denoising_step: false
weight_decay: 0.01
same_step_across_blocks: true
discriminator_lr_multiplier: 1.0
last_step_only: false
i2v: false
num_training_frames: 27
gc_interval: 100
context_noise: 0
causal: true

ckpt_step: 0
prompt_name: MovieGenVideoBench
prompt_path: prompts/MovieGenVideoBench.txt
eval_first_n: 64
num_samples: 1
height: 480
width: 832
num_frames: 81
logdir: null
model_save_dir: null
wandb_save_dir: null

model_kwargs:
  local_attn_size: -1
  sink_size: 1
  use_dual_channel_head: false
  use_gumbel_router: false
  global_layer_indices: null
  memory_size: 100
  anchor_frames: 2
  scene_change_tau: 0.6
